version: '2'

services:
  redis:
    image: redis:3.2
    command: redis-server
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5
     ports:
       - "9200:9200"
     environment:
       - http.host=0.0.0.0
       - transport.host=127.0.0.1
       - xpack.security.enabled=false
  mosquitto:
    image: tfgco/mosquitto_with_auth:0.0.1
    environment:
      - REDIS_PASS=nopass
      - REDIS_HOST=redis
    depends_on:
      - redis
  mqtt-history:
    build:
      context: ./
    environment:
      - MQTTHISTORY_MQTTSERVER_HOST=mosquitto
      - MQTTHISTORY_MQTTSERVER_PORT=1883
      - MQTTHISTORY_ELASTICSEARCH_HOST=http://elasticsearch:9200
      - MQTTHISTORY_REDIS_HOST=redis
    ports:
      - "8888:80"
      - "8883:443"
    depends_on:
      - redis
      - mosquitto
      - elasticsearch
